notifications:
  email: false
os: linux
language: python
python: 3.8
install:
# install binary packages
- travis_retry pip install --upgrade pip
- travis_retry pip install setuptools wheel
# install package
- travis_retry pip install -e .
# for tests:
- travis_retry pip install codecov coverage flake8
- pip freeze
script:
#- coverage run --source=ckanext setup.py test
#- coverage report -m
- flake8 ckanext
after_success:
- codecov
before_deploy:
#- python setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: "ci_dcor"
  password:
    secure: "XwsYRIFjg+w0B3//4WzBRXz8+j8txlECIRtQvDiLrF9VA5DUAPOEDPNFWDfY4aM6oK5xOqHYcErts0IEwvoiq5CCXtGmzYA2+ffJwv9satImfQqzoBRdXTt/SLkYCL47WbGVjixRi9UbhUrIG/EtN1UH+IzTh861/CjV5pOov2zCub8wcmEuTJA5XVBhw6S70pRLHnbwU0v8VE1jxujRKFqE5m4EhQXjqz5MqCO/GC4a4M1VVfat7/xDXW1aH+hMO7+yXOPS1lbtEhzt39UIelaRT6cl6c0YmxQ7gybcR1B9ViLtzVGP39Gym2BoO2Js3Bh71p4vnoFYV8zcyLuVRy5Z+Ap5w4F3KpT3fH6IaqzgiitdNHnJtPh2UAcyRM2odqp1ChS7qstcyhcK/8QxNj8/+WoQTM96dg5Msue5mbjNg7h5by3UKbiIIZq7IfmDtwOBeqp89o7ZJLz6M15s2pMdyJw6xIhwEKOSOO2tRE/ESFz/z4ETD4JHqi+TwGsO5XAcO7YdHM7em4T59eo0tQmWyGVMHaK1IB/v3t4GTy5CR08YyOQcNctWpJmPYcYck5b+JYq8O5VO2Jduj9OONcHdKkTtun7lLp0dQS9JEXnlRH+fy51b9n8r3ZyCzD50Pqu1ukTVRJDZJf+Tjcx6aeyCR+fjMJsA0iAqqLzrWUc="
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
