name: CI Test

on:
  push:
  pull_request:

# only allow one job to run
concurrency: general_workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file
      run: cp .env.example .env

    - name: Install Docker and Compose
      run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

    - name: Start Docker Compose services
      run: docker-compose -f docker-compose.ci.yml up -d

    - name: Wait for CKAN to be healthy
      run: docker-compose -f docker-compose.ci.yml exec dcor-ckan-dev bash -c "while ! wget -qO- http://localhost:5000; do sleep 5; done"

    - name: Run Tests
      run: bash ./docker-run-tests.sh

    - name: Upload Coverage to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml

    - name: Bring Down Docker Compose
      if: always()
      run: docker-compose -f docker-compose.ci.yml down
